# Generated by Django 5.1.6 on 2025-03-27 19:23

import manager.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='media/profile_pics/')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('main_interest', models.CharField(blank=True, max_length=255, null=True)),
                ('cpi', models.FloatField(blank=True, null=True)),
                ('university', models.CharField(blank=True, max_length=255, null=True)),
                ('skills_required', models.JSONField(default=list, validators=[manager.forms.validate_non_empty_list])),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('resume', models.FileField(upload_to='media/resumes/')),
            ],
        ),
    ]
