# Generated by Django 5.0.13 on 2025-03-29 21:34

import manager.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='media/profile_pics/')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('main_interest', models.CharField(blank=True, max_length=255, null=True)),
                ('cpi', models.FloatField(blank=True, null=True)),
                ('university', models.CharField(blank=True, max_length=255, null=True)),
                ('skills_required', models.JSONField(default=list, validators=[manager.utils.validate_non_empty_list])),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('resume', models.FileField(upload_to='media/resumes/')),
            ],
        ),
    ]
