# Generated by Django 5.1.6 on 2025-03-27 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateapplicationmodel',
            name='recruiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment', to='manager.recruitmentmodel'),
        ),
    ]
