# Generated by Django 5.1.6 on 2025-03-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_rename_recruiment_candidateapplicationmodel_recruitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateapplicationmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, null=True),
        ),
    ]
