# Generated by Django 5.1.6 on 2025-03-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_candidateapplicationmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateapplicationmodel',
            name='mailSent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
