# Generated by Django 5.1.6 on 2025-03-28 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_candidateapplicationmodel_mailsent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateapplicationmodel',
            name='mailSent',
        ),
    ]
