# Generated by Django 5.0.13 on 2025-03-29 19:40

import manager.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_remove_candidateapplicationmodel_mailsent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skills_required',
            field=models.JSONField(default=list, validators=[manager.utils.validate_non_empty_list]),
        ),
    ]
