# Generated by Django 5.1.6 on 2025-03-27 19:23

import django.db.models.deletion
import manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_details', models.TextField()),
                ('skills_required', models.JSONField(default=list, validators=[manager.models.validate_non_empty_list])),
                ('expected_salary', models.IntegerField()),
                ('minimum_experience', models.IntegerField()),
                ('form_status', models.BooleanField(blank=True, default='True', null=True)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruitments', to='myadmin.manager')),
            ],
        ),
    ]
