# Generated by Django 5.0.13 on 2025-03-29 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.PositiveIntegerField(help_text='Years of experience')),
                ('employee_type', models.CharField(choices=[('FR', 'Fresher'), ('JR', 'Junior'), ('SR', 'Senior'), ('TL', 'Team Lead'), ('MGR', 'Manager')], max_length=3)),
                ('salary_lpa', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Salary (LPA)')),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_manager', to='myadmin.manager')),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to='employee.profile')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_details', models.TextField()),
                ('skills_required', models.JSONField(default=list)),
                ('expected_salary', models.IntegerField()),
                ('minimum_experience', models.IntegerField()),
                ('form_status', models.BooleanField(blank=True, default=True, null=True)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('mailSent', models.BooleanField(blank=True, default=False, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruitments', to='myadmin.manager')),
            ],
        ),
    ]
