# Generated by Django 5.1.6 on 2025-03-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentmodel',
            name='mailSent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
