# Generated by Django 5.0.13 on 2025-03-29 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_profile_skills_required'),
        ('manager', '0002_recruitmentmodel_mailsent'),
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentmodel',
            name='form_status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruitmentmodel',
            name='skills_required',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.PositiveIntegerField(help_text='Years of experience')),
                ('employee_type', models.CharField(choices=[('FR', 'Fresher'), ('JR', 'Junior'), ('SR', 'Senior'), ('TL', 'Team Lead'), ('MGR', 'Manager')], max_length=3)),
                ('salary_lpa', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Salary (LPA)')),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_manager', to='myadmin.manager')),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to='employee.profile')),
            ],
        ),
    ]
