# Generated by Django 5.0.13 on 2025-04-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_employeemodel_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('skills', models.JSONField(default=list)),
                ('project_status', models.CharField(choices=[('IP', 'In Progress'), ('CP', 'Completed')], default='IP', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_member', models.ManyToManyField(related_name='team_member', to='manager.employeemodel')),
            ],
        ),
    ]
