# Generated by Django 5.0.13 on 2025-04-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_teammodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammodel',
            name='project_description',
            field=models.TextField(default='Give description of the project...'),
        ),
    ]
